### PR TITLE
Adding beforeEach/All + afterEach/All

### PR DESCRIPTION
**Pull request by PatrickBRT**

### CODE REVIEW

**Comment by jalada** [comment]
Thanks @PatrickBRT! We're honoured that Cavy is your first GitHub PR! :) It'd be interesting to hear how you are using Cavy. If you don't want to discuss publicly, please email team@pixielabs.io.

On to the PR...

1. What happens if two describe blocks have the same label in different spec files? Does it work?
2. Can you give an example use case for `{before,after}All`? It's best practice to keep tests independent of each other and their running order, and having `All` hooks doesn't encourage that, but I appreciate it's sometimes needed.
3. Could we make the before/after callback functions support `async` functions, so that users can perform asynchronous actions in their setup & teardown?
4. How might we support writing multiple before/after functions? Could we have an array of functions to call instead of just one?

**Comment by jalada** [comment]
As per the related issue, adding this to the 0.6.0 version target.

**Comment by PatrickBRT** [comment]
Hi!

yeah, its my first Github PR ;). 

I'm using cavy to automate testing. I do have unit-tests (jest) in place, but I'm lacking proper E2E tests, and thats where cavy comes into play ;-). Right now (hopefully subject to change) its more about checking basic functionality using E2E tests, to not burden the QA that much ;-). 

regarding your questions: 
Ad 1.) it didnt work beforehand, but i quickly changed the code to support that. Now those tests will get "merged" into one testSuite (and therefore are executed). Although i think that having the same describe-block-name is a thing one should avoid.

Ad 2.) tests should be totally independent of each other, as one runs into problems otherwise. Thats actually the main reason why I'm in need of setup/teardown functions, as I am using them for data-setup purposes.    
Example:  I do have a test "1" that adds element X to some collection and another test ("2") testing the removal of said element "X". If I do that without reseting the data-structure between tests, I end up with dependent tests (1 => 2 works, 2 => 1 won't).
Hope that made (at least some) sense ;-).

Ad 3.) I've added await to the function calls, should be fine now, right?

Ad 4.) See Ad 1 ;-).

**Comment by jalada** [comment]
I feel like merging `describe` blocks with the same label is a bit of a 'surprise'. Is there something else we could do?

What if we (initially) made it so setup and teardown functions were only available to be set on a per `spec` basis? e.g.

```javascript
export default function(spec) {
  spec.beforeEach(function() { });

  spec.describe('My feature', function() {
    spec.it('works', async function() {
      await spec.fillIn('Scene.TextInput', 'some string')
      await spec.press('Scene.button');
      await spec.exists('NextScene')
    });
  });
}
```

It perhaps reduces the usefulness, but it stops us from using the describe label as a key, which doesn't feel right. Is there another alternative?

Regarding Q/A two. I understand the use case you've described, but aren't you describing a use case for `beforeEach` not `beforeAll`?

**Comment by jalada** [comment]
Hi @PatrickBRT, any thoughts on the above?

**Comment by PatrickBRT** [comment]
Oh, sorry for the (very) late response. Seems like I somehow didnt see/get the notification about the thread-update in here. 

**Concerning your answer (per spec basis):**
adding the setup/teardown functions on a "per-spec-variable-basis" seems like a good idea, but we should sure focus on providing them on a more fine-grained level later on (say, per describe-block or similar)

**about the merging of describe blocks:**
i'm gonna think of that one a bit more, and try to come up with something. I'll keep you posted!

**beforeEach/beforeAll:** 
yeah it was a description of a beforeEach, my fault. a proper beforeAll thing would be setting up some mocks or something like that (my POV), for as long as cavy doesnt have some setup-functionality from a framework-perspective.

---

TL,DR.: I'll come up with a PR for the per-spec setup/teardown functions in the (very) near future and also will follow up with something that allows more fine-grained setup/teardown without merging testsuites

**Comment by cpetzel** [comment]
any movement on this?

**Comment by PatrickBRT** [comment]
@jalada: thanks! 👍 

resolved the merge conflicts (hope i didn't break anything while doing so ;-) ) and added some basic description to the Readme file.

**Comment by jalada** [comment]
Thanks @PatrickBRT! Quick question (for you too, @cpetzel, do you have a specific use case for `beforeAll/afterAll`? Just wondering what it will be used for once we add it.

**Comment by cpetzel** [comment]
So I think the `beforeEach` and `afterEach` functions make sense. However, the `beforeAll`, and `afterAll` don't necessarily make sense.. If I have multiple specs (in different files), only the first spec's `beforeAll` would actually get executed.

Also, I have some feedback about when these functions are executed...  In its current form, when Cavy's HOC Testable component is fully mounted (and therefore the app under test), it then starts executing the `before` functions from the first spec. This is a problem when your `before` functions need to drastically change the state of the app, which will alter which UI is shown as the app component mounts (ex, using react-navigation to navigate to a Login screen, or the Main screen based on whether or not the user is logged in). 

The `beforeEach` and `afterEach` would be great for mocking out things (which would be safe to do after the app is mounted). However, they don't help much if there is heavy logic in componentDidMount for your App, due to the lifecycle complexities mentioned above. 

I would prefer that these `before` functions are called before the Testable HOC is mounted for the first time, and also executed before the HOC is re-rendered for the next test case. This would benefit those who want to test the app initialization logic.

**Comment by jalada** [comment]
@cpetzel gotcha, so you want to be able to manipulate app state, etc. before the app is even mounted, and before it gets re-rendered and thus re-mounted (but after AsyncStorage is cleared)?

@PatrickBRT would your use-case suffer from that, or would it work too? If it's the former, maybe we need an option. If it's the latter, then we can just go with that.

**Comment by PatrickBRT** [comment]
@jalada : seems fine to me too. (to call beforeAll and afterAll earlier, if i got that right). I'll give it a shot and see what i come up with :-). Whats your personal take on that?

@cpetzel : concerning the "only the first spec's before/after are executed" => yeah, sadly. My first version (of this PR) had a support for multiple before/after functions, yet we opted (for a first version) for this (per-spec-basis) approach.

**Comment by jesouhaite08** [comment]
Any update on this? I'd love to use this feature. Thank you!

**Comment by em-cd** [comment]
hi @PatrickBRT, any update on this?

**Comment by zackzachariah** [comment]
Also going to ping on this thread, would be a great addition to Cavy!

**Comment by jalada** [comment]
@PatrickBRT  we're taking the learnings from this in to #123. Please take a look at the discussion in there, as well as our approach, and let us know if you have any thoughts.

We decided:

1. to take this piecemeal; start with `beforeEach` and work our way up from there,
2. to add an extra layer so that each spec file has a `TestScope` to itself where the `beforeEach` can be set, and
3. to focus on the use-case of using `beforeEach` to do some set up _before_ the app renders. For other use-cases, you can just write your own helper function and call it in each test case, or write a curried spec function.

You worked hard on this, and your contribution and insight has been key to finding what we think is the right solution. We'd love to send you some Cavy swag as a thank you; please can you email a postal address to david@pixielabs.io?

Looking forward to your feedback!

**Comment by jalada** [comment]
#123 is in 2.0.0. Would still really appreciate any feedback, so feel free to comment or send us an email. Thanks!

**Pull request closed without merging**
