### PR TITLE
 Implement `testable` Higher Order Component (HOC)

### PR DESCRIPTION
**Pull request by luizParreira**
- Implement component that helps injecting `ref` into a component by abstracting that into a HOC
- Documented additions

Note: This PR has potential conflicts with https://github.com/pixielabs/cavy/pull/77, will resolve them if any of them get merged.

### CODE REVIEW

**Comment by igorrfc** [comment]
Awesome catch, @luizParreira ! Cavy is great, but definitely needs stuff like that to be even better. Good job!

**Comment by jalada** [comment]
Agreed, thanks @luizParreira this is great. We'll get it sorted!

**Comment by jalada** [comment]
Hey @igorrfc @luizParreira. So that we get this API right, what is it about...

```javascript
const TestableTextInput = testable('testId')(TextInput);

render() {
   ...
   <TestableTextInput />
   ...
}
```

that you prefer over...

```javascript
const TestableTextInput = wrap(TextInput);

render () {
   ...
   <TestableTextInput ref={this.props.generateTestHook('testId')} />
   ...
}
```

Granted, you don't have to write out a `ref`. But for starters if you had two TextInputs you wanted to test you'd have to make two constants for the two different IDs. So it has its own set of drawbacks.

**Comment by luizParreira** [comment]
@jalada Yes, it does, unless you render the testable within your code and use whatever you would use to render the ids dynamically. Though that would look ugly at first, it could look better with some refactoring. I have yet to encounter that use case, I will be happy to post my solution when I do. 😅

**Comment by luizParreira** [comment]
@jalada We came across the need to identify our components based on their props, so we could uniquely identify them on our code. In order to do that, I have improved the HOC to be able to handle that case. Could you take a look and let me know what you think? 2b5b809

**Comment by em-cd** [comment]
Hi @luizParreira, we like this idea but don't want to introduce breaking changes right now and it feels like this is just personal preference. We're also hoping that React Native will implement accessibility ids which will completely change the way Cavy accesses components.

In the meantime, would you be interested in documenting your approach in the README? It does make for neater code, and people can implement it themselves 😄

**Comment by luizParreira** [comment]
@em-cd Thank you for replying. That would be great when react native does that. I dont mean to be rude, but I fail to see how this component is a breaking change? 🤔 

Anyways, I will set aside sometime in the future to document this, if thats the approach you guys prefer. :)

Best,
LP

**Comment by em-cd** [comment]
@luizParreira sorry, I got a little mixed up in my message 😅 It's not a breaking change, but it's adding a second way to do the same thing, which doesn't feel necessary. We'd rather give it as a suggestion than make it a second API that we need to support, because that would increase the risk of introducing breaking changes. Does that make more sense?

**Pull request closed without merging**
