### PR TITLE
Cavy tester

### PR DESCRIPTION
**Pull request by FLGMwt**
#142 

👋, back again 😎

This creates a `CavyTester` React Native sample app (`react-native init` from .60) which could ostensibly augment or replace `sample-app/CavyDirectory` as an e2e test bed for cavy itself.

I went for a bit more indirection than I typically prefer, but I was leaning towards the idea that the goals of "I want to test this API / behavior" and "I want to see how this API / behavior is tested" should involve as few files as possible. 

Ended up with the user workflow of:

1. Make a file that exports;
    - key: route name / alphanumeric id for test
    - label: short description of test
    - Screen: react component of app under test
    - spec: cavy spec testing app under test
2. In `src/App`, import * as MyScenario, add MyScenario to an array
3. 🎉

`src/App` does the work of:

- creating a home page listing the scenarios
- making routes for each scenario linked by the listing
- wrap the routed app in a Tester, provide the specs.

## Unsolicited rambling

I'm a bit torn about the responsibility of `CavyTester` as one of two things

- e2e testing for Cavy
- exemplary usage of Cavy in a real app

I think it really should be the `e2e` one, but you can't make it *not* function as the other to some degree.

That's really the only reason I went for `spec` being a full spec and didn't have `App` bake in the `describe(key, ...`, `it(label, ...`, and `press(key)` as foolproof as that would be.

Anyhow, lemme know if anyone has thoughts about that or the approach in general and I'll add some more coverage (fill, beforeEach, findComponent, etc).

### CODE REVIEW

**Comment by FLGMwt** [comment]
👀
image


friends

**Comment by jalada** [comment]
This is great @FLGMwt! Sorry for the radio silence. We've been super busy here at Pixie Labs. But this is on my list to take a look at today.

**Comment by jalada** [comment]
I've added a further layer of misdirection by making `spec.it` auto-navigate into the scene for the scenario. What do you think? @FLGMwt

**Comment by AbigailMcP** [comment]
Hi there @FLGMwt ! I realise this is an incredibly long time ago, but we're embarking on adding some new features to Cavy and as part of this drive I'd love to get this working and deployed!

Just a heads up really :) I'm working on bringing it up to date. and running in our CI environment.

**Comment by FLGMwt** [comment]
👋 Good to hear! Let me know if there's anything I can do to help : )

**Comment by jalada** [comment]
This is looking good! I got it running locally by following our CircleCI, the only difference was I had to install cocoapods the 'proper' way (with `gem install cocoapods`) probably because I'm using RVM. Not an issue for CircleCI, so happy to keep the config the same there.

:shipit:

**Comment by AbigailMcP** [comment]
Awesome! Thanks for the review @jalada - and of course @FLGMwt for the bulk of the work :)

@JonathanAndrews - if you're happy with how this works then I'll get it merged 🙌 

I'm also going to add a card to our roadmap to go back and tidy up our sample app, to turn it back into a simple real-world use-case example.

**Comment by JonathanAndrews** [comment]
Looks good to me 👍 :shipit:

**Pull request merged**
