### PR TITLE
Feature/typescript definitions

### PR DESCRIPTION
**Pull request by tyler-hoffman**
**Overview**
* Added `index.d.ts` for type definitions
* Added dev dependency of `@types/react` (needed for above type defs)
* Updated README for suggested usage of type defs.

### CODE REVIEW

**Comment by jalada** [comment]
Thanks Tyler! I'm not super familiar with TypeScript typedefs so this may be an obvious question. Is it normal to add a `@types/x` dev dependency like this?

Kind-of-related discussion point: TypeScript recommend that if a package is not written in TypeScript (like Cavy) the types are published to the `@types` organisation instead (see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). Thoughts?

**Comment by tyler-hoffman** [comment]
On the `@types/x` question: are you asking if that dependency should be included at all, or whether it should go in `dependencies` or `devDependencies`? That dependency is definitely needed, but perhaps it should be in `dependencies`, since cavy is a library. It's pretty standard to put the types in `devDependencies` when creating an app, though. I'll look into best practices on that a bit more.

Good point on publishing to `@types` instead of here. I think it's safe to close this PR if you'd like. I can take a look at publishing to `@types` (unless your team wants to do that).

**Comment by jalada** [comment]
@tyler-hoffman you did the hard work, so I think you should publish them! 🌟 😁

**Comment by tyler-hoffman** [comment]
Put PR in w/ DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33348

**Pull request closed without merging**
