### PR TITLE
Add judgement code for this.context.testHooks.add

### LINKED ISSUE #84: Show 'A component for xxxx has already been registered. Overwriting.' warning message.
Repeatedly entry detail page and go back to home page, will show warnning message.

stack

### PR DESCRIPTION
**Pull request by Kennytian**
close #84

### CODE REVIEW

**Comment by Kennytian** [comment]
@jalada I change other way, pull request this.

**Comment by jalada** [comment]
Hi @Kennytian. I'm not sure I understand what the purpose of this is? It makes it so by default Cavy doesn't do anything. Can you explain the problem you're having?

**Comment by johnmarinelli** [comment]
@jalada @Kennytian I also noticed this issue, and tried for a little while to hack together a log message verbosity setting Cavy that could control this.   

However, it looks like it's already [built in to React Native](https://facebook.github.io/react-native/docs/debugging.html#warnings) (as of 0.52 at least).  You can disable warnings individually, or as a whole.  

The lines that I used were:

```
import { YellowBox } from 'cavy'
YellowBox.ignoreWarnings(['A component for'])
```

The fact that the YellowBox api only checks for message prefixes is kind of annoying, though.  Maybe you could namespace Cavy error messages with a prefix?  ¯\_(ツ)_/¯

**Comment by em-cd** [comment]
It sounds like this isn't an issue anymore, @Kennytian feel free to open another PR for this if you think it is.

**Pull request closed without merging**
