### PR TITLE
New Context API

### PR DESCRIPTION
**Pull request by AbigailMcP**
This PR is based off #117 so that we can make use of the new Context API for React, and eventually hooks.

We used to use `getChildContext` to ensure that the `testHookStore` was in context when running our tests, but now we can use a context provider as recommended by React.

### CODE REVIEW

**Comment by jalada** [comment]
@AbigailMcP how d'you feel about react being a peer dependency? It matches the way react-native works, in that react-native also has react as a peer dependency, and we have react-native as a peer dependency. But it's good to include it explicitly because we import context from React.

**Comment by AbigailMcP** [comment]
@jalada I'm happy with React as a peer dependency especially since this is what React Native does 👌

**Comment by jalada** [comment]
Note for merging: Requires a major version bump

**Comment by jalada** [comment]
Closing in favour of #120

**Pull request closed without merging**
