### PR TITLE
[FEATURE] Timeout if RN app doesn't boot

### PR DESCRIPTION
**Pull request by JonathanAndrews**
[Roadmap ticket](https://www.pivotaltracker.com/story/show/172696463)
### Includes
- change api for CavyReporter
- `this.reporter.onStart()` creates a websocket connection with Cavy cli
- `this.reporter.onFinsh()` sends the results to Cavy cli via the websocket

### Testing
To test you need use this [branch](https://github.com/pixielabs/cavy-cli/tree/timeout-if-app-doesnt-boot) of Cavy CLI.
See this [PR](https://github.com/pixielabs/cavy-cli/pull/29).

### Compatibility
- This is a backwards compatible change. Propose a minor version bump

### CODE REVIEW

**Comment by jalada** [comment]
Most important thing is to avoid a breaking change; we should make sure the native reporter still works (do we have a test suite for that? 🤔 ).

Philosophically, we need to make sure it feels like we're enhancing the existing reporter API rather than restructuring it. We should plan ahead to make sure our roadmap matches up with the direction we're taking so we don't have to keep changing the API. We should also (as per what Abigail said) document what the new API looks like. It might be worth going through a bit of a brainstorming exercise on what the API should look like that is a little forward thinking? Does that make sense?

**Comment by AbigailMcP** [comment]
Thanks @jalada ! @JonathanAndrews is working on making this a non-breaking change.

**Comment by jalada** [comment]
This is looking good! What's left?

**Comment by AbigailMcP** [comment]
> This is looking good! What's left?

Looks pretty scheet @JonathanAndrews !

Re what's left, @jalada we did discuss having the reporter `type` in this release too (`simple` vs `in progress`)? Although, we will only need to distinguish between the two when in progress results is in.

**Comment by jalada** [comment]
@AbigailMcP got it! Yeah that can be part of the other PR, right?

**Comment by AbigailMcP** [comment]
@JonathanAndrews - let's get this over the line! Can you confirm what kind of version bump this is?

Have we deprecated our own Native Reporter? If so, let's capture addressing this somewhere.

**Comment by JonathanAndrews** [comment]
> Are we deprecating our own Native Reporter? i.e. will using the Native Reporter now give a warning message? If so, let's capture addressing this somewhere.

I've added two tickets to the Roadmap icebox. 
[New Native Reporter](https://www.pivotaltracker.com/story/show/173153781)
[Update Docs](https://www.pivotaltracker.com/story/show/173153487)

**Pull request merged**
