### PR TITLE
Fix defaultProps warning when using `wrap` function

### PR DESCRIPTION
**Pull request by luizParreira**
# Changes

- When using the `wrap` function, react-native would warn that
`defaultProps` should be a static prop, because of that we are
now using recompose's `toClass` function, that does the same
thing, without the warnings.
- Remove `create-react-class` dependency, since its no longer needed
- Added `recompose` dependency, in order to use `toClass` HOC

Closes https://github.com/pixielabs/cavy/issues/76

### CODE REVIEW

**Comment by jalada** [comment]
Thanks @luizParreira! We'll take a look at this as soon as we can :)

**Comment by jalada** [comment]
@luizParreira Is there any point in keeping `wrap` around? Should we not just point people to use `toClass` instead?

**Comment by luizParreira** [comment]
@jalada Yes, that is something to consider if the user has `recompose` added to his dependencies. However, if the user does not use `recompose`, it would be great if `cavy` provided an API to do that, since its a requirement for the functional components. In addition of that, it wouldn't add any breaking changes to future versions and `recompose` is already being added to `cavy` through #78 anyways.

**Comment by jalada** [comment]
@luizParreira we've just updated our README and soft-deprecated `wrap()` in favour of pointing people to Recompose. There's really no need for Cavy to try and replicate functionality much better served by the Recompose team.

We'll be properly deprecating it in a future version.

**Pull request closed without merging**
